#
# (C) Copyright 2017 Rockchip Electronics Co., Ltd.
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += test-rockchip.o
obj-y += test-brom-dnl.o
obj-$(CONFIG_IRQ) += test-timer.o
obj-$(CONFIG_DM_KEY) += test-key.o
obj-$(CONFIG_MMC) += test-emmc.o
obj-$(CONFIG_DM_REGULATOR)+= test-regulator.o
obj-$(CONFIG_RKNAND) += test-rknand.o
obj-$(CONFIG_GMAC_ROCKCHIP) += test-eth.o
obj-$(CONFIG_RK_IR) += test-ir.o
obj-$(CONFIG_ROCKCHIP_VENDOR_PARTITION) += test-vendor-storage.o
