#
# (C) Copyright 2017 Rockchip Electronics Co., Ltd.
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += test-rockchip.o
obj-y += test-timer.o
obj-y += test-key.o
obj-y += test-emmc.o
obj-y += test-regulator.o
obj-y += test-rknand.o
obj-$(CONFIG_GMAC_ROCKCHIP) += test-eth.o
obj-$(CONFIG_RK_IR) += test-ir.o
