language: c

env:
  global:
    - TRAVIS_SECURE_ENV_VARS=true
    - ARCH=arm64
    - CROSS_COMPILE=aarch64-linux-gnu-

matrix:
  include:
    - env:
      - TARGET_BOARD=odroid_rk3568

addons:
  apt:
    packages:
    - cppcheck
    - sloccount
    - sparse
    - bc
    - build-essential
    - libsdl1.2-dev
    - python
    - python-virtualenv
    - swig
    - libpython-dev
    - gcc-powerpc-linux-gnu
    - iasl
    - grub-efi-ia32-bin
    - rpm2cpio
    - wget
    - device-tree-compiler
    - lzop
    - gcc
    - libncurses5-dev

git:
  depth: 1

before_install:
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install libc6-i386 lib32stdc++6 lib32z1; fi

install:

before_script:
  - mkdir -p /opt/toolchains
  - wget https://releases.linaro.org/components/toolchain/binaries/7.4-2019.02/aarch64-linux-gnu/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz
  - tar xvf gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz -C /opt/toolchains/
  - wget https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v10.2.0-1.2/xpack-riscv-none-embed-gcc-10.2.0-1.2-linux-x64.tar.gz
  - tar xvf xpack-riscv-none-embed-gcc-10.2.0-1.2-linux-x64.tar.gz -C /opt/toolchains/
  - export PATH=$TOPDIR/opt/toolchains/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin:/opt/toolchains/xpack-riscv-none-embed-gcc-10.2.0-1.2/bin:$PATH

script:
  - ./make.sh ${TARGET_BOARD}

before_deploy:
  - export RELEASE_VERSION="${TARGET_BOARD}-${TRAVIS_BUILD_NUMBER}"
  - tar czf u-boot-${RELEASE_VERSION}.tar.gz uboot.img
  - git config --global user.name ${GIT_USER_NAME}
  - git config --global user.email ${GIT_USER_EMAIL}
  - export REMOTE_URL=`git config --get remote.origin.url`
  - export GIT_TAG="travis/${RELEASE_VERSION}"
  - git tag ${GIT_TAG} -a -m "Tagged by Travis CI"
  - git push --quiet https://${PRIVATE_ACCESS_TOKEN}@${REMOTE_URL#$"https://"} ${GIT_TAG}

deploy:
  provider: releases
  api_key: ${PRIVATE_ACCESS_TOKEN}
  file_glob: true
  file: u-boot-${RELEASE_VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
