obj-$(CONFIG_AML_LCD) += aml_lcd.o aml_lcd_common.o aml_lcd_gpio.o \
		aml_lcd_clk_config.o aml_lcd_phy_config.o aml_lcd_debug.o \
		aml_lcd_bl.o aml_lcd_unifykey.o aml_lcd_tcon.o
obj-$(CONFIG_AML_LCD_TV) += lcd_tv/
obj-$(CONFIG_AML_LCD_TABLET) += lcd_tablet/
obj-$(CONFIG_AML_LCD_EXTERN) += lcd_extern/
obj-$(CONFIG_AML_LOCAL_DIMMING) += aml_ldim/
obj-$(CONFIG_AML_BL_EXTERN) += bl_extern/
