#
# (C) Copyright 2015
#

#EXTRA_CFLAGS = -Idrivers/video/include/

obj-$(CONFIG_AML_HDMITX20) += hdmitx20.o

hdmitx20-y := reg_ops.o hdmitx_set.o hdmitx_tvenc.o enc_clk_config.o
#aml_hdmitx20-$(CONFIG_AML_HDMITX20_HDCP) += hdmitx_hdcp.o

