#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#


#obj-$(CONFIG_AML_NAND) := aml_nand.o
obj-$(CONFIG_AML_NAND) += dev/
#obj-$(CONFIG_AML_NAND) += logic/
obj-$(CONFIG_AML_NAND) += logiclib/
obj-$(CONFIG_AML_NAND) += phy/

