#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_DM_FUEL_GAUGE) += fuel_gauge_uclass.o

obj-$(CONFIG_POWER_FG_MAX17042) += fg_max17042.o
