
include $(TOPDIR)/config.mk

LIB	:= $(obj)libamlnf_logic.o

$(obj)/libamlnf_logic.o:
	@cp ./libamlnf_logic_140724.z ../../../build/drivers/amlnf/logic/libamlnf_logic.o

#########################################################################

include $(SRCTREE)/rules.mk

sinclude $(obj).depend

#########################################################################
