#
# (C) Copyright 2017 Rockchip Electronics Co., Ltd.
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += irq-gic.o
obj-y += irq-gpio.o
obj-y += irq-generic.o
obj-y += irq-gpio-switch.o
obj-y += virq.o
