
obj-y	:= clock.o sdio.o gpio.o
obj-y	+= usb.o
obj-y   += bl31_apis.o
obj-y	+= watchdog.o
obj-$(CONFIG_AML_HDMITX20) += hdmitx20/
obj-y	+= timer.o
obj-y	+= mailbox.o
obj-y   += gate_init.o
obj-y   += power_cal.o
obj-$(CONFIG_CMD_PLLTEST)	+= pll.o
obj-$(CONFIG_CMD_AML_MTEST) += core.o
