#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += aml_nand.o m3_nand.o aml_env.o aml_dtb.o aml_key.o rsv_manage.o nand_flash.o cmd_amlmtd.o boot.o
